name: shartflix
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.1
  firebase_crashlytics: ^4.3.10
  dartz: ^0.10.1
  connectivity_plus: ^6.1.4
  firebase_core: ^3.15.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.6
  # flutter_launcher_icons ve flutter_native_splash dev_dependencies'e taşındı
  # çünkü bunlar sadece build zamanında kullanılır, runtime'da değil.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.4 # ✅ dev_dependencies altında

# Flutter ile ilgili ana yapılandırmalar
flutter:
  uses-material-design: true

  # Uygulama varlıkları (assets)
  assets:
    - assets/images/
    - assets/lang/
    - assets/fonts/ # Bu satırı koruyun, altında tek tek dosyaları da listeleyebilirsiniz
    - assets/images/film.jpg
    - assets/icons/icon.png
    - assets/icons/like.png
    - assets/icons/like_bg.png
    - assets/icons/like_filled.png
    - assets/icons/eclipse.png
    - assets/icons/premium.png
    - assets/icons/heart.png
    - assets/icons/muscle.png
    - assets/icons/more_heart.png

  # Özel fontlar
  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid_Circular_A_Regular.ttf
        - asset: assets/fonts/Euclid_Circular_A_Medium.ttf
          weight: 500
        # Eğer varsa diğer Euclid Circular A varyantları:
        # - asset: assets/fonts/Euclid_Circular_A_Bold.ttf
        #   weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        # Eğer varsa diğer Montserrat varyantları:
        # - asset: assets/fonts/Montserrat-Light.ttf
        #   weight: 300
        # - asset: assets/fonts/Montserrat-Italic.ttf
        #   style: italic

# flutter_launcher_icons yapılandırması (flutter: bloğunun dışında)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sinFlixLogo.png" # Simge dosyanızın yolu

# flutter_native_splash yapılandırması (flutter: bloğunun dışında)
flutter_native_splash:
  color: "#000000"
  image: assets/images/sinFlixLogo.png
  # brand_image: assets/images/brand_logo.png
  # color_dark: "#042a49"
  # image_dark: assets/images/splash_logo_dark.png
  # android_gravity: center
  # ios_content_mode: center

  android_12:
    image: assets/images/sinFlixLogo.png
    color: "#000000"
    # icon_background_color: "#111111"
    # image_dark: assets/images/splash_logo_dark.png
    # color_dark: "#042a49"
    # icon_background_color_dark: "#111111"
